version: '3.8'

x-noises-api-labels: &noises-api-labels
  labels:
    - traefik.enable=true
    - traefik.docker.network=monitoring
    - traefik.http.routers.noises-api-http.rule=Host(`noises.api.${DOMAIN?Variable not set}`)
    - traefik.http.routers.noises-api-http.entrypoints=http
    #- traefik.http.routers.noises-api-http.middlewares=admin-auth
    - traefik.http.routers.noises-api-http.service=noises-api
    - traefik.http.routers.noises-api-http.middlewares=https-redirect
    - traefik.http.routers.noises-api-https.rule=Host(`noises.api.${DOMAIN?Variable not set}`)
    - traefik.http.routers.noises-api-https.entrypoints=https
    - traefik.http.routers.noises-api-https.middlewares=admin-auth
    - traefik.http.routers.noises-api-https.tls=true
    - traefik.http.routers.noises-api-https.service=noises-api
    - traefik.http.routers.noises-api-https.tls.certresolver=le
    - traefik.http.services.noises-api.loadbalancer.server.port=80

x-smokes-api-labels: &smokes-api-labels
  labels:
    - traefik.enable=true
    - traefik.docker.network=monitoring
    - traefik.http.routers.smokes-api-http.rule=Host(`smokes.api.${DOMAIN?Variable not set}`)
    - traefik.http.routers.smokes-api-http.entrypoints=http
    #- traefik.http.routers.smokes-api-http.middlewares=admin-auth
    - traefik.http.routers.smokes-api-http.service=smokes-api
    - traefik.http.routers.smokes-api-http.middlewares=https-redirect
    - traefik.http.routers.smokes-api-https.rule=Host(`smokes.api.${DOMAIN?Variable not set}`)
    - traefik.http.routers.smokes-api-https.entrypoints=https
    - traefik.http.routers.smokes-api-https.middlewares=admin-auth
    - traefik.http.routers.smokes-api-https.tls=true
    - traefik.http.routers.smokes-api-https.service=smokes-api
    - traefik.http.routers.smokes-api-https.tls.certresolver=le
    - traefik.http.services.smokes-api.loadbalancer.server.port=80

x-no-labels: &no-labels
  labels:
    - traefik.enable=false
    
x-service: &service
  logging:
    driver: json-file
    options:
      max-size: "100m"
      max-file: "2"
  restart: always
  networks:
    - monitoring

services:
  noises-api:
    container_name: noises-api
    image: xrevo/useless-soft-noises-api:220907-2148
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          cpus: '0.01'
          memory: 50M
      <<: *noises-api-labels
    <<: *noises-api-labels
    <<: *service
    
  smokes-api:
    container_name: smokes-api
    image: xrevo/useless-soft-smokes-api:220907-2148
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          cpus: '0.01'
          memory: 50M
      <<: *smokes-api-labels
    <<: *smokes-api-labels
    <<: *service
    
  sensors:
    container_name: sensors
    image: xrevo/useless-soft-sensors:220907-2148
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          cpus: '0.01'
          memory: 50M
      <<: *no-labels
    <<: *no-labels
    <<: *service
    
  alerts:
    container_name: alerts
    image: xrevo/useless-soft-alerts:220907-2148
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          cpus: '0.01'
          memory: 50M
      <<: *no-labels
    <<: *no-labels
    <<: *service


x-network: &network
  external: true

networks:
  monitoring:
    name: monitoring
    <<: *network