version: "3"
services:
  # back-ends
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./output:/etc/output:rw # Store the logs
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - zipkin-all-in-one

  tempo:
    # https://github.com/grafana/tempo/releases
    image: grafana/tempo:1.4.1
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yml:/etc/tempo.yaml
    restart: unless-stopped
    ports:
      - 3200:3200  # tempo
      - 4007:4317  # otlp grpc

  loki:
    # https://github.com/grafana/loki/releases
    image: grafana/loki:2.5.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki.yml:/etc/loki/local-config.yaml
    restart: unless-stopped
    ports:
      - 3100:3100


  # https://hub.docker.com/r/grafana/grafana
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./grafana/config:/etc/grafana/provisioning
      # - ./grafana/data:var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_SECRET_KEY: mysuperSECRETkey!
      GF_SERVER_ROOT_URL: http://localhost:3001
      GF_SERVER_ENABLE_GZIP: "true"
      GF_SECURITY_COOKIE_SECURE: "false"
      GF_SNAPSHOTS_EXTERNAL_ENABLED: "false"
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - 3001:3000
    user: root